# Generated by Django 6.0.4 on 2026-05-22 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('store', '0006_alter_home_product_price_alter_shop_page_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='product_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invioce_id',
            field=models.CharField(default='PENDING', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shop_page'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='razorpay_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.razorpay_order'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customername',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='phonenumber',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shippingaddress',
            field=models.TextField(default='Not Provided', max_length=500),
        ),
    ]
