# Generated by Django 6.0.4 on 2026-05-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_invoice_invoice_id_remove_invoice_order_id_and_more'),
        ('store', '0006_alter_home_product_price_alter_shop_page_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(blank=True, to='store.shop_page'),
        ),
    ]
