# Generated by Django 6.0.4 on 2026-05-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_invoice_product_invoice_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invioce_id',
            new_name='invoice_id',
        ),
    ]
