# Generated by Django 6.0.4 on 2026-05-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('main_image', models.ImageField(upload_to='images')),
                ('hover_image', models.ImageField(upload_to='images')),
                ('price', models.IntegerField()),
                ('product_id', models.CharField(max_length=20)),
            ],
        ),
    ]
