# Generated by Django 6.0.4 on 2026-05-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutpage_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images')),
                ('image2', models.ImageField(upload_to='images')),
                ('image3', models.ImageField(upload_to='images')),
                ('image4', models.ImageField(upload_to='images')),
                ('image5', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField(max_length=1000)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='contactpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='shop_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('product_id', models.CharField(max_length=20)),
                ('product_decription', models.TextField(max_length=1000)),
                ('washcare', models.TextField(max_length=1000)),
                ('garment_details', models.TextField(max_length=1000)),
                ('product_image1', models.ImageField(upload_to='images')),
                ('product_image2', models.ImageField(upload_to='images')),
                ('product_image3', models.ImageField(upload_to='images')),
                ('product_image4', models.ImageField(upload_to='images')),
                ('product_image5', models.ImageField(upload_to='images')),
                ('product_image6', models.ImageField(upload_to='images')),
                ('product_image7', models.ImageField(upload_to='images')),
                ('product_image8', models.ImageField(upload_to='images')),
                ('product_image9', models.ImageField(upload_to='images')),
            ],
        ),
    ]
