# Generated by Django 6.0.4 on 2026-05-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_aboutpage_images_community_contactform_contactpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='message',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
