# Generated by Django 6.0.4 on 2026-05-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
