# Generated by Django 6.0.5 on 2026-05-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cartitem_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shop_page',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
