"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import environ
import dj_database_url  
# i will find all the database, apikeys, mcp servers 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env_path = os.path.join(BASE_DIR, '.env')
if os.path.exists(env_path):
    load_dotenv(env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY or SECRET_KEY.strip() == '':
    SECRET_KEY = 'django-insecure-y51^kaytzqy*+xel6*v#-ln6p(kdx6kudaaa@r(_kf(02%@onv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
if os.getenv('VERCEL_URL'):
    ALLOWED_HOSTS.append(os.getenv('VERCEL_URL'))
    ALLOWED_HOSTS.append('.vercel.app')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'payments'
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],    
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.cart_count',
            ],
        },
    },
]

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"), 
]
MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')


WSGI_APPLICATION = 'ecommerce.wsgi.application'


import logging
from urllib.parse import urlparse

logger = logging.getLogger(__name__)

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
db_url = os.environ.get('DATABASE_URL')

# Check if we are running on Vercel (where filesystem is read-only)
IS_VERCEL = os.getenv('VERCEL') == '1' or os.getenv('VERCEL_URL') is not None
SQLITE_FALLBACK_PATH = '/tmp/db.sqlite3' if IS_VERCEL else 'db.sqlite3'
SQLITE_FALLBACK_URL = f'sqlite:///{SQLITE_FALLBACK_PATH}'

def validate_and_parse_db_url(url):
    """
    Validates the database URL, masks credentials for safe logging,
    and returns a parsed configuration or falls back to SQLite gracefully.
    """
    if not url or not url.strip():
        logger.warning(f"DATABASE_URL is not set or is empty. Falling back to SQLite ({SQLITE_FALLBACK_PATH}).")
        return SQLITE_FALLBACK_URL
    
    try:
        parsed = urlparse(url)
        # Mask password in URL for secure logging
        masked_url = url
        if parsed.password:
            masked_url = url.replace(parsed.password, "********")
            
        if parsed.scheme not in ('postgres', 'postgresql', 'sqlite'):
            logger.error(
                f"Unsupported database scheme '{parsed.scheme}' in DATABASE_URL: {masked_url}. "
                f"Only PostgreSQL and SQLite are supported. Falling back to SQLite ({SQLITE_FALLBACK_PATH})."
            )
            return SQLITE_FALLBACK_URL
            
        logger.info(f"Database connection URL validated: {masked_url}")
        return url
    except Exception as e:
        logger.error(f"Error parsing DATABASE_URL: {str(e)}. Falling back to SQLite ({SQLITE_FALLBACK_PATH}).")
        return SQLITE_FALLBACK_URL

# Securely validate the database URL
db_url_validated = validate_and_parse_db_url(db_url)

try:
    DATABASES = {
        'default': dj_database_url.parse(db_url_validated)
    }
except Exception as e:
    logger.critical(
        f"Failed to parse database configuration using dj_database_url: {str(e)}. "
        f"Falling back to emergency SQLite database ({SQLITE_FALLBACK_PATH}) to prevent application crash."
    )
    DATABASES = {
        'default': dj_database_url.parse(SQLITE_FALLBACK_URL)
    }

# SECURITY & PRIVILEGE COMPLIANCE NOTE:
# - Ensure that the database user configured in DATABASE_URL has limited permissions (least privilege).
# - Do not use the superuser account (e.g. postgres) for daily application operations in production.
# - Keep credentials stored securely in the environment (.env) and never hardcode them in version control.





# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# django razorpay configuration
env = environ.Env()
env_file = os.path.join(BASE_DIR, '.env')
if os.path.exists(env_file):
    environ.Env.read_env(env_file)

RAZORPAY_KEY_ID = env('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = env('RAZORPAY_KEY_SECRET', default='')

# Security Settings for Cookie Protection
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# Disable all HTTPS/SSL Redirection and HSTS for local development
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')